name: Docker CI

env:
    IMAGE_NAME: OpenSfM
    IMAGE_VERSION: 1.0.0
    REGISTRY: ghcr.io
    IMAGE_PREFIX: m2rt

on: [push, pull_request]


jobs:

  build-test:
    name: Build docker and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            tags: |
                type=ref,event=branch,suffix=-{{ sha }}
                type=ref,event=tag
                type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }},${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ env.IMAGE_NAME }}:latest
            labels: ${{ steps.meta.outputs.labels }}